config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: "", path_names: { sign_in: "login", sign_out: "logout", sign_up: "register"}
  resources :portfolios, except: [:show]
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  resources :blogs
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
	enum status: { draft: 0, published: 1 }
	extend FriendlyId
  friendly_id :title, use: :slugged

  validates_presence_of :title, :body

  belongs_to :topic
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
	has_many :technologies, dependent: :destroy
	accepts_nested_attributes_for :technologies,
																reject_if: lambda { |attrs| attrs["name"].blank? }

	validates_presence_of :title, :body, :main_image, :thumb_image
	include Placeholder

	def self.angular
		where(subtitle: "Angular")
	end

	scope :ruby_on_rails, -> { where(subtitle: "Ruby on Rails")}

	after_initialize :set_defaults

	def set_defaults
		self.main_image ||= Placeholder.image_generator(height: "600", width: "400")
		self.thumb_image ||= Placeholder.image_generator(height: "350", width: "200")
	end
end

app/models/skill.rb
class Skill < ApplicationRecord
	include Placeholder
	validates_presence_of :title, :percent_utilized

	after_initialize :set_defaults

	def set_defaults
		self.badge ||= Placeholder.image_generator(height: "250", width: "250")
	end
end

app/models/technology.rb
class Technology < ApplicationRecord
  belongs_to :portfolio
end

app/models/topic.rb
class Topic < ApplicationRecord
	validates_presence_of :title

	has_many :blogs
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates_presence_of :name

  def first_name
    self.name.split.first
  end

  def last_name
    self.name.split.last
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include DeviseWhitelist
	include SetSource
	include CurrentUserConcern
	include DefaultPageContent
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy ]
  layout "blog"

  # GET /blogs or /blogs.json
  def index
    @blogs = Blog.all
    @page_title = "My Portfolio Blog"
  end

  # GET /blogs/1 or /blogs/1.json
  def show
    @page_title = @blog.title
    @seo_keywords = @blog.body
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: "Blog was successfully created." }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: "Blog was successfully updated." }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/controllers/concerns/current_user_concern.rb
module CurrentUserConcern
	extend ActiveSupport::Concern

	def current_user
		super || guest_user
	end

	def guest_user
		OpenStruct.new(name: "Guest", 
									 first_name: "Guest", 
									 last_name: "Guest", 
									 email: "guest@email.com"
									 )
	end
end

app/controllers/concerns/default_page_content.rb
module DefaultPageContent
	extend ActiveSupport::Concern

	included do
		before_action :set_page_defaults
	end

	def set_page_defaults
		@page_title = "Devcamp Portfolio | My Portfolio Website"
		@seo_keywords = "Walter De Guzman porfolio"
	end
end

app/controllers/concerns/devise_whitelist.rb
module DeviseWhitelist
	extend ActiveSupport::Concern

	included do 
		before_action :configure_permitted_parameters, if: :devise_controller?

		def configure_permitted_parameters
			devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
			devise_parameter_sanitizer.permit(:account_update, keys: [:name])
		end
	end
end

app/controllers/concerns/placeholder.rb
module Placeholder
	extend ActiveSupport::Concern

	def self.image_generator(height:, width:)
		"http://placehold.it/#{height}x#{width}"
	end
end

app/controllers/concerns/set_source.rb
module SetSource
	extend ActiveSupport::Concern

	included do
		before_action :set_source
	end

	def set_source
		session[:source] = params[:q] if params[:q]
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @posts = Blog.all
    @skills = Skill.all
  end

  def about
  end

  def contact
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
layout "portfolio"

	def index
		@portfolio_items = Portfolio.all
	end
	
	def new
		@portfolio_items = Portfolio.new
    3.times { @portfolio_items.technologies.build }
	end

	def create
    @portfolio_items = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio_items.save
        format.html { redirect_to portfolios_path, notice: "Your portfolio item is now created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit
  	@portfolio_items = Portfolio.find(params[:id])
  end

  def update
  	@portfolio_items = Portfolio.find(params[:id])

    respond_to do |format|
      if @portfolio_items.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: "Portfolio was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def show
  	@portfolio_items = Portfolio.find(params[:id])
  end

  def destroy
  	@portfolio_items = Portfolio.find(params[:id])

  	@portfolio_items.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: "Portfolio was removed." }
    end
  end

  private

  def portfolio_params
    params.require(:portfolio).permit(:title,
                                      :subtitle, 
                                      :body, 
                                      technologies_attributes: [:name]
                                      )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def login_helper
		if current_user.is_a?(User)
    	link_to "Logout", destroy_user_session_path, method: :delete 
    else 
    	(link_to "Register", new_user_registration_path) +
    	" "  +
    	(link_to "Login", new_user_session_path)
    end 
	end

end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.body %></td>
        <td><%= link_to blog.status, toggle_status_blog_path(blog) %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Delete post', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @blog.body %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="keywords" content=<%= @seo_keywords %> />

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= render "shared/nav", location: 'top' %>

    <%= login_helper %>

    <%= yield %>

    <% if session[:source] %>
      <p>Thanks for visiting me from <%= session[:source] %></p>
    <% end %>
  </body>
</html>

app/views/layouts/blog.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="keywords" content=<%= @seo_keywords %> />

    <%= stylesheet_link_tag 'blogs', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= login_helper %>

    <%= yield %>

    <%= render "shared/nav", location: 'bottom' %>

    <% if session[:source] %>
      <p>Thanks for visiting me from <%= session[:source] %></p>
    <% end %>
  </body>
</html>

app/views/layouts/portfolio.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="keywords" content=<%= @seo_keywords %> />

    <%= stylesheet_link_tag 'portfolios', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= render "shared/nav", location: 'top' %>

    <%= login_helper %>

    <%= yield %>

    <% if session[:source] %>
      <p>Thanks for visiting me from <%= session[:source] %></p>
    <% end %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>Hi, <%= current_user.first_name %></h1>
<p>Find me in app/views/pages/home.html.erb</p>

<h1>Blog Posts</h1>
<%= @posts.inspect %>

<h1>Skills</h1>
<%= @skills.inspect %>

<hr>

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio_items) do |f| %>
	<div class="field">
		<%= f.label :title %>
		<%= f.text_field :title %>
	</div>

	<div class="field">
		<%= f.label :subtitle %>
		<%= f.text_field :subtitle %>
	</div>

	<div class="field">
		<%= f.label :body %>
		<%= f.text_area :body %>
	</div>

	<ul>
		<%= f.fields_for :technologies do |technology_form| %>
			<li>
				<%= technology_form.label :name %>
				<%= technology_form.text_field :name %>
			</li>
		<% end %>
	</ul>

	<div class="field">
		<%= f.submit %>
	</div>
<% end %>

app/views/portfolios/edit.html.erb
<h1>Edit this portfolio item</h1>

<%= render 'form', portfolio_item: @portfolio_items %>

app/views/portfolios/index.html.erb
<h1>Portfolio Items</h1>

<%= link_to "Create New Item", new_portfolio_path %>

<% @portfolio_items.each do |portfolio_item| %>
	<p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></p>
	<p><%= portfolio_item.subtitle %></p>
	<p><%= portfolio_item.body %></p>
	<p><%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %></p>
	<p>
		<%= link_to "Edit", edit_portfolio_path(portfolio_item) %>
		<%= link_to 'Delete Portfolio Item', portfolio_path(portfolio_item), method: :delete, data: { confirm: 'Are you sure?' } %>
	</p>
	<hr></hr>

<% end %>

app/views/portfolios/new.html.erb
<h1>Create new portfolio item</h1>

<%= render 'form', portfolio_item: @portfolio_items %>

app/views/portfolios/show.html.erb
<p> <%= image_tag @portfolio_items.main_image %> </p>

<h1><%= @portfolio_items.title %></h1>

<em><%= @portfolio_items.subtitle %></em>

<p><%= @portfolio_items.body %></p>

<h2>Technologies Used:</h2>

<% @portfolio_items.technologies.each do |x| %>
<p><%= x.name %></p>
<% end %>

app/views/shared/_nav.html.erb
<div class="<% location %>">
  <div><%= link_to "Home", root_path %></div>
  <div><%= link_to "About", about_path %></div>
  <div><%= link_to "Contact", contact_path %></div>
  <div><%= link_to "Blogs", blogs_path %></div>
  <div><%= link_to "Portfolios", portfolios_path %></div>
</div>